### ISSUE TITLE
PowerPC SDL2 is built --disable-joystick, so SDL_GameController is unavailable

### ISSUE THREAD

**Issue by matthewdeaves** [matthewdeaves/old-mac-quake2#9]
Every PowerPC SDL2 build in this fleet is configured `--disable-joystick --disable-haptic` (see `scripts/build-ppc-panther.sh` and `scripts/build-ppc-tiger.sh` in the Half-Life repo, which is where `panther-sdl2` is built).

That means **`SDL_GameController` is not available on any PowerPC slice**. It has not mattered so far because nothing here uses it, but it blocks anything that does. Aleph One uses the GameController API, so it would need this resolved before it could run on these machines.

The unknown, and it is a real one: **nobody appears to have published a joystick-enabled PPC SDL2 build.** Research did not settle whether the joystick/HID backend actually compiles against the 10.3.9 / 10.4u SDKs, or whether it was disabled here to dodge a build failure rather than as a size or simplicity choice. That question needs answering before anyone plans work that depends on it.

To do:
- find out WHY it is disabled: a genuine build failure on the old SDKs, or convenience
- try a build with joystick enabled against the 10.3.9 SDK and record what happens, either way
- if it does build, decide whether to enable it by default or keep it opt-in
- if it does not, write down the exact failure so the next person does not repeat the experiment

Worth recording even if the answer is "cannot be done": right now the fleet has an untested assumption where it should have a measured fact.

Raised from cross-repo review, 2026-08-21.

**Comment by matthewdeaves** [comment]
## Measured: it is a genuine build failure, not convenience

Tested 2026-08-21 on `mini-intel`. Same `panther-sdl2` checkout (`1e4b81c`),
same compiler (`gcc-4.0`), same flags (`-arch ppc -mcpu=7400 -faltivec
-fno-math-errno`), configured `--enable-joystick --enable-haptic`. **Only the
SDK varies:**

| SDK | `configure` | `make` | joystick objects |
|---|---|---|---|
| 10.3.9 | exit 0, reports `joystick haptic` enabled | **exit 2** | none |
| 10.5 | exit 0 | **exit 0, no errors** | `SDL_sysjoystick.o`, `SDL_gamecontroller.o`, `SDL_syshaptic.o` |

So `--disable-joystick` on the PowerPC slices is forced by the SDK floor.

### Mechanism, and why the error is misleading

SDL2's only macOS joystick backend is written against the **IOHIDManager** API.
The failure is *not* a missing header, it is 200-odd lines of:

```
src/joystick/darwin/SDL_sysjoystick_c.h:29: error: syntax error before 'IOHIDElementRef'
src/joystick/darwin/SDL_sysjoystick.c:42:   error: syntax error before 'hidman'
src/joystick/darwin/SDL_sysjoystick.c:100:  error: 'IOHIDValueRef' undeclared
```

`SDL_sysjoystick_c.h` includes `<IOKit/hid/IOHIDLib.h>`, and that header
**exists in 10.3.9 and 10.4u**, so the `#include` succeeds. What differs is
what it pulls in:

```
10.3.9 / 10.4u  IOKit/hid/  ->  IOHIDKeys.h  IOHIDLib.h  IOHIDUsageTables.h
10.5            IOKit/hid/  ->  ... IOHIDBase.h  IOHIDDevice.h  IOHIDElement.h
                                    IOHIDManager.h  IOHIDQueue.h  IOHIDValue.h ...
```

`IOHIDDeviceRef`, `IOHIDElementRef` and `IOHIDManagerRef` are declared in
`IOHIDBase.h` / `IOHIDDevice.h` / `IOHIDElement.h`, which do not exist below
10.5. The types are undeclared, so every use of them is a syntax error.

### Consequence

`SDL_GameController` still *compiles* on PowerPC, so nothing fails to link.
It sits on the dummy joystick driver and reports zero devices, which is why
this looks like "controllers just don't work" rather than a build problem.

### A route out exists

SDL **1.2**'s darwin joystick backend uses the older IOCFPlugIn /
`IOHIDDeviceInterface` API (`kIOHIDDeviceInterfaceID`, `IOCFPlugInInterface`),
and `IOCFPlugIn.h` **is** present in both the 10.3.9 and 10.4u SDKs. That is
exactly why the SDL 1.2 sister ports have working joysticks on Panther and
Tiger and the SDL2 one does not.

Porting that backend onto SDL2's `SDL_sysjoystick.h` driver interface, inside
our own `panther-sdl2` fork and conditional on the SDK lacking IOHIDManager,
would restore gamepads on PowerPC. Not attempted, for two reasons worth stating
plainly:

1. It is a hand-written HID backend going into a shipped SDL.
2. **It cannot be verified without a USB gamepad plugged into a PowerPC Mac.**
   Nothing in the bench harness substitutes for that.

Scoped and left open rather than guessed at.

### Also corrected

The related claim that "SDL2 never supported 10.3/10.4" is wrong as written,
and so is treating it as fully supported. The accurate form is **video, audio
and events work; joystick, GameController and haptic do not**. The shipped
Half-Life port is the evidence for the first half, this build is the evidence
for the second.

**Comment by matthewdeaves** [comment]
Closing: the premise does not hold for this port.

This repo does not use `panther-sdl2`, or SDL2 at all, on PowerPC. `build-ppc-panther.sh` and `build-ppc-tiger.sh` are Half-Life's build drivers and build Half-Life's statically linked SDL2. Nothing in them touches this tree.

Measured off the shipped DMG:

```
$ lipo -info .../Contents/MacOS/SDL.framework/Versions/A/SDL
x86_64 i386 ppc ppc970
$ lipo -info .../Contents/MacOS/SDL2.framework/Versions/A/SDL2      # QuakeSpasm only
x86_64 i386 arm64
```

The PowerPC slices link **SDL 1.2**. SDL2 appears only on Intel and arm64, where the joystick backend was never in question. And SDL 1.2's PowerPC slice already has joystick support compiled in:

```
$ nm -g SDL(ppc) | grep SDL_Joystick
_SDL_JoystickOpen
_SDL_JoystickOpened
_SDL_NumJoysticks
```

So there is nothing disabled here to re-enable. `SDL_GameController` is an SDL2-only API and does not exist in SDL 1.2 at any version, on any platform, so a port pinned to SDL 1.2 could not offer it regardless of build flags. Anything wanting the GameController API on this fleet needs the Half-Life port's SDL2, not a flag change here.

The underlying question was real and has been answered on the repo it actually applies to: matthewdeaves/old-mac-half-life-1#2. It was not convenience. SDL2's macOS joystick backend needs the 10.5-era IOHIDManager API and fails to build against the 10.3.9 SDK. Our `panther-sdl2` fork now carries a legacy IOHIDDeviceInterface backend, and `SDL_GameController` works on both PowerPC slices there as of v1.9.2.
